### ISSUE TITLE
Totally broken.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [writeas/Read.as#10]
read.as > certificate expired page > 404
![Screenshot_20230215_201244](https://user-images.githubusercontent.com/42837531/219142539-8c687e0c-ca9a-4081-ba8d-2b9811262d7a.png)

**Comment by thebaer** [comment]
This seems to be the demo site, not a bug in the application, so I'll close this.

**Comment by roke-julian-lockhart** [comment]
@thebaer, where should this be reported to, then?

**Comment by thebaer** [comment]
Email is best, but I've seen it now. No plans to revive this site for now, as this project is on hold.
