### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by c-cesar** [writeas/Read.as#8]
Following the instructions I managed to run the server, and the database connection is working, as I get the "User not found" and "Incorrect password." messages on wrong data. But when using the correct login, the page refresh and show the login form again.

My browsers says the page isn't storing any cookie, so, I gees this is the problem, but I can't find the bug on code.
Tested on Firefox and Chrome-like browser.

**Comment by thebaer** [comment]
Hmm, is there anything appearing in the server logs? Are you logged in to any other site on localhost? And did you generate the cookie signing / encryption keys by running `keys.sh`?

**Comment by c-cesar** [comment]
the keys was

**Comment by c-cesar** [comment]
The keys where generated in the install process
```
$ ls keys

cookies_auth.aes256  cookies_enc.aes256  README.md
```

The logs don't show anything significant to me:
```
2018/10/13 14:00:05 "GET /" 200 176.841µs "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" "localhost:8080"

2018/10/13 14:00:08 "POST /api/auth/login" 302 1.00667255s "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" "localhost:8080"

2018/10/13 14:00:08 "GET /" 200 129.068µs "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" "localhost:8080"
```

I don't have any other active session on localhost but tested on private window with same result.

**Comment by c-cesar** [comment]
Found the issue.
I didn't changed the host in `config.json` from `https://read.as` to `localhost`.
The server started silently with a incorrect host, so I think we still have a bug, but not related to login.

**Comment by thebaer** [comment]
Ah, makes sense. I've added some logging to display the URL upon launch, so maybe others will catch this. Otherwise I'll make sure the configuration steps are clearer in the future.
